language: cpp

## Enable sudo (set explicitly although it is enabled by default when docker is
#  running as a service
sudo: required

## Ensures the virtualization environment runs as Ubuntu 14.04 Trusty
dist: trusty

## Environment variables
#
#  The 'global' section defines variables common for all jobs
env:
  global:
    - COMPILER_VERSION=
    - DEPLOY_PACKAGE=false
    - DIST_NAME=ubuntu
    - DIST_VERSION=xenial
    - DOCKER_COMPOSE_VERSION=1.16.1
    - DRIZZLE_TEST_EXIT_ERROR_ON_SKIP=0
    - MAKE_TARGET=check
    - MYSQL_PASSWORD=''
    - MYSQL_PORT=3306
    - MYSQL_SERVER=127.0.0.1
    - MYSQL_USER=root
    - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"
    - SKIP_TEST_ON_ERROR=0

## Build steps for all jobs
before_install:
  - ./travis_configure.sh before_install
before_script:
  - ./travis_configure.sh before_script
script:
  - ./travis_configure.sh run_tests

## Defines the jobs to run in each stage
#
#  Travis combines the variables defined in env.global with the variables
#  defined for each job
#
#  The resulting build matrix is as follows:
#
#  | os     | dist   | compiler  | make targets | deploy |
#  |--------|--------|-----------|--------------|--------|
#  | linux  | ubuntu | clang     | check        | no     |
#  | linux  | ubuntu | gcc       | check deb    | yes    |
#  | linux  | centos | gcc       | check rpm    | yes    |
#  | osx    | sierra | clang¹    | check        | no     |
#
#  Linux based builds are run in docker containers using docker-compose.
#
#  OSX based builds are done by a third-party provider
#
#  ¹ The compiler reported is the Apple LLVM version
#
jobs:
  templates:
    # Global config for builds on linux
    - &linux-build
      cache: ccache
      os:
        - linux
      services:
        - docker
    # Global config for builds on osx
    - &osx-build
      os: osx
      compiler: clang

  include:
    # Sets up the build environment, compiles the code and runs tests
    - <<: *linux-build
      env:
        COMPILER_VERSION=4.9 MAKE_TARGET="$MAKE_TARGET:deb"
      deploy:
          provider: script
          script: beaver bintray upload -D $DIST_VERSION -N build/pkg/deb/*.deb
          skip_cleanup: true
          on:
              tags: true # must be a git tag
              repo: sociomantic-tsunami/libdrizzle-redux # must be upstream
              condition: $DIST_VERSION = 'xenial' && $CC = 'gcc'
    - <<: *linux-build
      env:
        CXX=clang++ CC=clang COMPILER_VERSION=3.9
    - <<: *linux-build
      env:
        DIST_NAME=centos DIST_VERSION=7 MAKE_TARGET=rpm
    - <<: *osx-build
